# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# To build website from project directory, excute this command:
# jekyll build -d /web/cs/web/sites/groupsight/ --config _config_dev.yml

# Site settings
title: GroupSight 
subtitle: Workshop on Human Computation for Image and Video Analysis
email: groupsight@outlook.com
organization: GroupSight Workshop HCOMP 2017
description: > # this means to ignore newlines until "baseurl:"
  The Second GroupSight Workshop on Human Computation for Image and Video Analysis is a workshop at the Fifth AAAI Conference on Human Computation and Crowdsourcing (HCOMP 2017) to be held October 24 - November 26, 2017 in Quebec City, USA.

# Build settings
markdown: kramdown
url: "http://groupsight.github.io"
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
